### PR TITLE
added support for "background" scan

### PR DESCRIPTION
**Pull request by rfelten**
Hi Bob,
love your handy tool. I've added support for the 'background' mode of spectral scan where a channel is observed continuously.

Minor changes consist:
- fixed frequency range to match outside US -> maybe this should read out from ``iw reg get`
- minor refactoring

Please note: Due lack of ath10k hardware, **this stuff is only tested on ath9k_htc** :(

BR
Robert

### CODE REVIEW

**Comment by bcopeland** [comment]
Awesome, thanks!   ath10k doesn't really work correctly anyway, so no worries on that.  Will merge after I get some time to review.

**Comment by bcopeland** [comment]
Nice work!  Sorry for the delay.

**Comment by rfelten** [comment]
Hi Bob,

thanks for merging!

FYI: I was not aware that GitHub treat additional commits to an PR also as part of the PR. That is the reason why so much multiple new featues (HT40, multiple device support, other power calculation etc) also ended up here.

**Comment by bcopeland** [comment]
On Wed, Feb 24, 2016 at 05:58:17AM -0800, Robert Felten wrote:

> Hi Bob,
> 
> thanks for merging!
> 
> FYI: I was not aware that GitHub treat additional commits to an PR
> also as part of the PR. That is the reason why so much multiple new
> featues (HT40, multiple device support, other power calculation etc)
> also ended up here.

Yeah, I did see all the new stuff and played around with them some.  I
don't mind having those new features in there even in a beta state so
long as the main functionality is working.  But if there's something
you think I should drop for now, let me know.

## 

Bob Copeland %% http://bobcopeland.com/

**Pull request merged**
